# Generated by Django 5.0.6 on 2024-07-08 11:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('port', '0003_blog_resume'),
    ]

    operations = [
        migrations.CreateModel(
            name='Yourself',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('phone', models.CharField(max_length=13)),
                ('degree', models.CharField(max_length=100)),
                ('city', models.CharField(max_length=100)),
                ('email', models.CharField(max_length=50)),
                ('about_you', models.TextField()),
                ('address', models.CharField(max_length=50)),
                ('facebook', models.CharField(default='default_facebook_value', max_length=300)),
                ('twitter', models.CharField(default='default_facebook_value', max_length=300)),
                ('linkedin', models.CharField(default='default_facebook_value', max_length=300)),
                ('github', models.CharField(default='default_facebook_value', max_length=300)),
            ],
        ),
    ]
